import {
  Transaction,
  Budget,
  FinancialGoal,
  Investment,
  DebtItem,
  SmartAlert,
} from '@/lib/types/finance';

export const DEMO_TRANSACTIONS: Omit<Transaction, 'id' | 'userId' | 'createdAt'>[] = [
  // Income
  {
    date: '2026-09-01',
    amount: 120000,
    type: 'income',
    category: 'Salary',
    merchant: 'Tech Innovations Ltd',
    description: 'Monthly Salary Credit',
    isRecurring: true,
    recurringFrequency: 'monthly',
    paymentMethod: 'Net Banking',
  },
  {
    date: '2026-09-15',
    amount: 25000,
    type: 'income',
    category: 'Freelance',
    merchant: 'Client Consulting',
    description: 'Web Architecture Advisory',
    isRecurring: false,
    paymentMethod: 'UPI',
  },
  // Fixed Bills & Housing
  {
    date: '2026-09-02',
    amount: 32000,
    type: 'expense',
    category: 'Housing & Rent',
    merchant: 'Hiranandani Estate Rent',
    description: 'Apartment monthly rent',
    isRecurring: true,
    recurringFrequency: 'monthly',
    paymentMethod: 'Net Banking',
  },
  {
    date: '2026-09-05',
    amount: 21500,
    type: 'expense',
    category: 'Debt & EMI',
    merchant: 'HDFC Bank Home Loan',
    description: 'Home loan monthly EMI',
    isRecurring: true,
    recurringFrequency: 'monthly',
    paymentMethod: 'Net Banking',
  },
  {
    date: '2026-09-06',
    amount: 3200,
    type: 'expense',
    category: 'Utilities',
    merchant: 'Bescom Electricity',
    description: 'Power utility bill',
    isRecurring: true,
    recurringFrequency: 'monthly',
    paymentMethod: 'UPI',
  },
  {
    date: '2026-09-07',
    amount: 999,
    type: 'expense',
    category: 'Utilities',
    merchant: 'Airtel Broadband',
    description: 'Fiber internet bill',
    isRecurring: true,
    recurringFrequency: 'monthly',
    paymentMethod: 'Credit Card',
  },
  // Subscriptions
  {
    date: '2026-09-08',
    amount: 649,
    type: 'expense',
    category: 'Subscriptions',
    merchant: 'Netflix Premium',
    description: 'Monthly 4K plan',
    isRecurring: true,
    recurringFrequency: 'monthly',
    paymentMethod: 'Credit Card',
  },
  {
    date: '2026-09-09',
    amount: 119,
    type: 'expense',
    category: 'Subscriptions',
    merchant: 'Spotify Individual',
    description: 'Audio streaming subscription',
    isRecurring: true,
    recurringFrequency: 'monthly',
    paymentMethod: 'Credit Card',
  },
  // Food & Dining
  {
    date: '2026-09-10',
    amount: 4850,
    type: 'expense',
    category: 'Food & Dining',
    merchant: 'D-Mart Supermarket',
    description: 'Monthly household grocery run',
    paymentMethod: 'Debit Card',
  },
  {
    date: '2026-09-12',
    amount: 850,
    type: 'expense',
    category: 'Food & Dining',
    merchant: 'Swiggy Gourmet',
    description: 'Weekend dinner delivery',
    paymentMethod: 'UPI',
  },
  {
    date: '2026-09-14',
    amount: 1450,
    type: 'expense',
    category: 'Food & Dining',
    merchant: 'Social Pub & Bistro',
    description: 'Team dinner celebration',
    paymentMethod: 'Credit Card',
  },
  {
    date: '2026-09-18',
    amount: 1250,
    type: 'expense',
    category: 'Food & Dining',
    merchant: 'Zomato Gold',
    description: 'Family weekend lunch',
    paymentMethod: 'UPI',
  },
  // Transit
  {
    date: '2026-09-11',
    amount: 4200,
    type: 'expense',
    category: 'Transportation',
    merchant: 'HPCL Fuel Station',
    description: 'Car fuel refill',
    paymentMethod: 'Credit Card',
  },
  {
    date: '2026-09-16',
    amount: 680,
    type: 'expense',
    category: 'Transportation',
    merchant: 'Uber Premier',
    description: 'Airport cab commute',
    paymentMethod: 'UPI',
  },
  // Shopping & Tech (Occasional)
  {
    date: '2026-09-20',
    amount: 6500,
    type: 'expense',
    category: 'Shopping',
    merchant: 'Amazon Electronics',
    description: 'Ergonomic mechanical keyboard and desk accessories',
    paymentMethod: 'Credit Card',
  },
  // Healthcare
  {
    date: '2026-09-22',
    amount: 1850,
    type: 'expense',
    category: 'Healthcare',
    merchant: 'Apollo Pharmacy',
    description: 'Health supplements and medicine',
    paymentMethod: 'UPI',
  },
  // Previous month comparative transactions
  {
    date: '2026-08-01',
    amount: 120000,
    type: 'income',
    category: 'Salary',
    merchant: 'Tech Innovations Ltd',
    description: 'Monthly Salary Credit',
    isRecurring: true,
    paymentMethod: 'Net Banking',
  },
  {
    date: '2026-08-05',
    amount: 32000,
    type: 'expense',
    category: 'Housing & Rent',
    merchant: 'Hiranandani Estate Rent',
    description: 'August rent',
    paymentMethod: 'Net Banking',
  },
  {
    date: '2026-08-12',
    amount: 6800,
    type: 'expense',
    category: 'Food & Dining',
    merchant: 'Dining & Groceries',
    description: 'August groceries and dining',
    paymentMethod: 'UPI',
  },
];

export const DEMO_BUDGETS: Omit<Budget, 'id' | 'userId'>[] = [
  {
    category: 'Food & Dining',
    limit: 12000,
    period: 'monthly',
    alertThresholdPercent: 80,
    notes: 'Includes groceries and eating out',
  },
  {
    category: 'Transportation',
    limit: 6000,
    period: 'monthly',
    alertThresholdPercent: 75,
    notes: 'Fuel and cab fares',
  },
  {
    category: 'Shopping',
    limit: 10000,
    period: 'monthly',
    alertThresholdPercent: 80,
    notes: 'Discretionary apparel and gadgets',
  },
  {
    category: 'Utilities',
    limit: 5000,
    period: 'monthly',
    alertThresholdPercent: 85,
    notes: 'Power, broadband, mobile recharge',
  },
  {
    category: 'Subscriptions',
    limit: 1500,
    period: 'monthly',
    alertThresholdPercent: 90,
    notes: 'Streaming services',
  },
];

export const DEMO_GOALS: Omit<FinancialGoal, 'id' | 'userId' | 'createdAt'>[] = [
  {
    name: 'Emergency Buffer Fund',
    targetAmount: 300000,
    currentAmount: 195000,
    targetDate: '2027-03-31',
    monthlyContribution: 17500,
    category: 'Emergency Fund',
    status: 'active',
    priority: 'high',
  },
  {
    name: 'M4 MacBook Pro & Studio Display',
    targetAmount: 220000,
    currentAmount: 140000,
    targetDate: '2026-12-15',
    monthlyContribution: 27000,
    category: 'Laptop',
    status: 'active',
    priority: 'medium',
  },
  {
    name: 'Japan Autumn Vacation',
    targetAmount: 250000,
    currentAmount: 110000,
    targetDate: '2027-10-01',
    monthlyContribution: 11000,
    category: 'Travel',
    status: 'active',
    priority: 'low',
  },
];

export const DEMO_INVESTMENTS: Omit<Investment, 'id' | 'userId'>[] = [
  {
    symbol: 'NIFTYBEES',
    name: 'Nippon India Nifty 50 ETF',
    assetType: 'stocks',
    quantity: 650,
    buyPrice: 242.5,
    currentPrice: 271.8,
    investedAmount: 157625,
    currentValue: 176670,
    returnAmount: 19045,
    returnPercentage: 12.08,
  },
  {
    symbol: 'PPFAS-FLEXI',
    name: 'Parag Parikh Flexi Cap Fund',
    assetType: 'mutual_funds',
    quantity: 2150,
    buyPrice: 72.4,
    currentPrice: 86.9,
    investedAmount: 155660,
    currentValue: 186835,
    returnAmount: 31175,
    returnPercentage: 20.03,
  },
  {
    symbol: 'TCS',
    name: 'Tata Consultancy Services',
    assetType: 'stocks',
    quantity: 25,
    buyPrice: 3820,
    currentPrice: 4210,
    investedAmount: 95500,
    currentValue: 105250,
    returnAmount: 9750,
    returnPercentage: 10.21,
  },
  {
    symbol: 'GOLD-BEES',
    name: 'Nippon India Gold ETF',
    assetType: 'gold',
    quantity: 120,
    buyPrice: 58.5,
    currentPrice: 68.2,
    investedAmount: 70200,
    currentValue: 81840,
    returnAmount: 11640,
    returnPercentage: 16.58,
  },
];

export const DEMO_DEBTS: Omit<DebtItem, 'id' | 'userId'>[] = [
  {
    name: 'HDFC Home Loan',
    principal: 2800000,
    interestRate: 8.75,
    tenureMonths: 240,
    emi: 24749,
    remainingBalance: 2415000,
    startDate: '2023-01-15',
    category: 'Home Loan',
    extraMonthlyPayment: 2500,
  },
  {
    name: 'ICICI Car Loan',
    principal: 750000,
    interestRate: 9.1,
    tenureMonths: 60,
    emi: 15610,
    remainingBalance: 320000,
    startDate: '2024-03-10',
    category: 'Car Loan',
    extraMonthlyPayment: 1500,
  },
];

export const DEMO_ALERTS: Omit<SmartAlert, 'id' | 'userId'>[] = [
  {
    title: 'Food & Dining approaching limit',
    message: 'You have used 70% of your ₹12,000 Food & Dining budget with 12 days remaining.',
    type: 'warning',
    category: 'budget_exceeded',
    date: '2026-09-18',
    read: false,
    actionUrl: '/budgets',
  },
  {
    title: 'Upcoming Home Loan EMI in 4 days',
    message: 'HDFC Home Loan EMI of ₹24,749 will be auto-debited on 5th of this month.',
    type: 'info',
    category: 'upcoming_emi',
    date: '2026-09-20',
    read: false,
    actionUrl: '/debts',
  },
  {
    title: 'Emergency buffer on track',
    message: 'Your emergency fund now covers 3.2 months of living expenses. Keep going!',
    type: 'success',
    category: 'goal_behind',
    date: '2026-09-21',
    read: true,
    actionUrl: '/goals',
  },
];
